"""empty message

Revision ID: 12930c97abe
Revises: 367a141415b
Create Date: 2015-02-21 23:50:43.218492

"""

# revision identifiers, used by Alembic.
revision = '12930c97abe'
down_revision = '367a141415b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
