"""empty message

Revision ID: 1dc0f9b0aee
Revises: 86fb103078
Create Date: 2015-02-21 21:54:37.579653

"""

# revision identifiers, used by Alembic.
revision = '1dc0f9b0aee'
down_revision = '86fb103078'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
