"""empty message

Revision ID: 297a2a32c82
Revises: 12930c97abe
Create Date: 2015-02-22 00:02:00.508543

"""

# revision identifiers, used by Alembic.
revision = '297a2a32c82'
down_revision = '12930c97abe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
