"""empty message

Revision ID: 2c5d311ba58
Revises: 297a2a32c82
Create Date: 2015-02-22 00:24:30.259963

"""

# revision identifiers, used by Alembic.
revision = '2c5d311ba58'
down_revision = '297a2a32c82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
