"""empty message

Revision ID: 367a141415b
Revises: 1dc0f9b0aee
Create Date: 2015-02-21 21:56:26.461459

"""

# revision identifiers, used by Alembic.
revision = '367a141415b'
down_revision = '1dc0f9b0aee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
