"""empty message

Revision ID: 43f2c8c7ef0
Revises: 5ac9e4574c3
Create Date: 2015-02-21 14:04:41.581257

"""

# revision identifiers, used by Alembic.
revision = '43f2c8c7ef0'
down_revision = '5ac9e4574c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
