"""empty message

Revision ID: 4f23639b762
Revises: b6b04c43a6
Create Date: 2015-02-21 18:39:29.944037

"""

# revision identifiers, used by Alembic.
revision = '4f23639b762'
down_revision = 'b6b04c43a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
