"""empty message

Revision ID: 5ac9e4574c3
Revises: 44bff9bf6f4
Create Date: 2015-02-21 13:47:12.442212

"""

# revision identifiers, used by Alembic.
revision = '5ac9e4574c3'
down_revision = '44bff9bf6f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
