"""empty message

Revision ID: 86fb103078
Revises: c5cf6740cf
Create Date: 2015-02-21 19:43:18.767930

"""

# revision identifiers, used by Alembic.
revision = '86fb103078'
down_revision = 'c5cf6740cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
