"""empty message

Revision ID: 984ed83c51
Revises: 4f23639b762
Create Date: 2015-02-21 19:13:53.928092

"""

# revision identifiers, used by Alembic.
revision = '984ed83c51'
down_revision = '4f23639b762'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
