"""empty message

Revision ID: b6b04c43a6
Revises: 2882b6ca455
Create Date: 2015-02-21 18:34:44.840837

"""

# revision identifiers, used by Alembic.
revision = 'b6b04c43a6'
down_revision = '2882b6ca455'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
