"""empty message

Revision ID: c5cf6740cf
Revises: 984ed83c51
Create Date: 2015-02-21 19:17:50.813833

"""

# revision identifiers, used by Alembic.
revision = 'c5cf6740cf'
down_revision = '984ed83c51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
